// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCQ_sxLgE4DJX1ouH5mHydo19r0llbC38',
    appId: '1:1034418380087:web:3d40894b2287e04a7e8eb2',
    messagingSenderId: '1034418380087',
    projectId: 'iron-pillar',
    authDomain: 'iron-pillar.firebaseapp.com',
    storageBucket: 'iron-pillar.firebasestorage.app',
    measurementId: 'G-1HCVNXDPQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvzH8zcgJ7M0Qh456h0EtxzgAXMe9byhY',
    appId: '1:1034418380087:android:ba72dd87e9f6b1ae7e8eb2',
    messagingSenderId: '1034418380087',
    projectId: 'iron-pillar',
    storageBucket: 'iron-pillar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8wUPmx3C7avP2Ogf8EJFHqjLd-PBb_M4',
    appId: '1:1034418380087:ios:87afca9fc0846d247e8eb2',
    messagingSenderId: '1034418380087',
    projectId: 'iron-pillar',
    storageBucket: 'iron-pillar.firebasestorage.app',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8wUPmx3C7avP2Ogf8EJFHqjLd-PBb_M4',
    appId: '1:1034418380087:ios:87afca9fc0846d247e8eb2',
    messagingSenderId: '1034418380087',
    projectId: 'iron-pillar',
    storageBucket: 'iron-pillar.firebasestorage.app',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCQ_sxLgE4DJX1ouH5mHydo19r0llbC38',
    appId: '1:1034418380087:web:72e1f4173d9b6dfa7e8eb2',
    messagingSenderId: '1034418380087',
    projectId: 'iron-pillar',
    authDomain: 'iron-pillar.firebaseapp.com',
    storageBucket: 'iron-pillar.firebasestorage.app',
    measurementId: 'G-3ZG0D0WQGE',
  );
}
